server:
  port: 8082

spring:
  application:
    name: payment
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      transactional-id-prefix: tx-payment-producer-
      properties:
        enable.idempotence: true
    consumer:
      group-id: payment-group

  datasource:
    url: jdbc:postgresql://localhost:5432/store_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

kafka:
  payment:
    topic-name: "payed_orders"
  orders:
    topic-name: "new_orders"

order-service:
  host: localhost
  port: 8081