server:
  port: 8083

spring:
  application:
    name: shipping
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      transactional-id-prefix: tx-shipping-producer-
      properties:
        enable.idempotence: true
    consumer:
      group-id: shipping-group

kafka:
  payment:
    topic-name: "payed_orders"
  shipping:
    topic-name: "sent_orders"

order-service:
  host: localhost
  port: 8081